name: Deploy
on:
    workflow_run:
        workflows: ['Test']
        branches: [main]
        types:
            - completed

jobs:
    test:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Check out repository code.
              uses: actions/checkout@v2
            - name: Install Node.js.
              uses: actions/setup-node@v2
              with:
                  node-version: '14.17.1'
            - name: Cache Yarn cache.
              uses: c-hive/gha-yarn-cache@v2
            - name: Install project dependencies.
              run: yarn --prefer-offline  --frozen-lockfile
            - name: Deploy.
              env:
                  ENVIRONMENT: production
              run: yarn deploy
